# Scaffolding generated by Casein v5.1.1.5

module Casein
  class InitiationClassesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Initiation classes'
  		@initiation_classes = InitiationClass.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View initiation class'
      @initiation_class = InitiationClass.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new initiation class'
    	@initiation_class = InitiationClass.new
    end

    def create
      @initiation_class = InitiationClass.new initiation_class_params
    
      if @initiation_class.save
        flash[:notice] = 'Initiation class created'
        redirect_to casein_initiation_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new initiation class'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update initiation class'
      
      @initiation_class = InitiationClass.find params[:id]
    
      if @initiation_class.update_attributes initiation_class_params
        flash[:notice] = 'Initiation class has been updated'
        redirect_to casein_initiation_classes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this initiation class'
        render :action => :show
      end
    end
 
    def destroy
      @initiation_class = InitiationClass.find params[:id]

      @initiation_class.destroy
      flash[:notice] = 'Initiation class has been deleted'
      redirect_to casein_initiation_classes_path
    end
  
    private
      
      def initiation_class_params
        params.require(:initiation_class).permit(:name)
      end

  end
end